import { v4 as uuid } from "uuid";
import { MigrationInterface, QueryRunner, Table } from "typeorm";

export class CreateCurrency1620767713169 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: "currencys",
        columns: [
          {
            name: "id",
            type: "varchar",
            isPrimary: true,
          },
          {
            name: "currency_pair",
            type: "varchar",
            isUnique: true,
          },

          {
            name: "created_at",
            type: "datetime",
            default: "now()",
          },
          {
            name: "updated_at",
            type: "datetime",
            isNullable: true,
          },
        ],
      })
    );

    await queryRunner.manager
      .createQueryBuilder()
      .insert()
      .into("currencys")
      .values([
        {
          id: uuid(),
          currency_pair: "BNB_BTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_AAVE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_AKRO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_AMP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_ARDR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_ATOM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_AVA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_BAT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_BCH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_BCHA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_BCHSV",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_BID",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_BNT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_BTS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_CHR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_CVC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_DASH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_DCR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_DOGE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_DOT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_EOS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_ETC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_ETH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_ETHBNT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_EXE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_FARM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_FCT2",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_FOAM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_FRONT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_FUND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_FXC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_FIL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_GAS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_GLM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_HGET",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_INJ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_KNC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_KLV",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_LEND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_LINK",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_LOOM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_LPT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_LRC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_LSK",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_LTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_MANA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_MATIC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_MDT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_MKR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_NEO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_NMR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_NXT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_OMG",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_POLY",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_QTUM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_REN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_REPV2",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SAND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SENSO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SNT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SNX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_STEEM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_STORJ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_STPT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_STR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SWAP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SWFTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SWINGBY",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_SXP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_TRU",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_TRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_TUSD",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_WBTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_WRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_XEM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_XMR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_XRP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_XTZ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_ZEC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BTC_ZRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BUSD_BNB",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "BUSD_BTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "DAI_BTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "DAI_ETH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_BAL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_BAT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_BCH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_COMP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_EOS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_ETC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_TUSD",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_ZEC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "ETH_ZRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "PAX_BTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "PAX_ETH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_AMP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_AVA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_BNB",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_BRG",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_BTT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_CHR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_ETH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_FUND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_FXC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_JST",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_KLV",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_LINK",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_MATIC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_MDT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_NEO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_PEARL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_SNX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_STEEM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_STPT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_SUN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_SWFTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_SWINGBY",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_SXP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_TAI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_VSP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_WIN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_WRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_XRP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TRX_XTZ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TUSD_BTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "TUSD_ETH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_ATOM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_BCH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_BCHSV",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_BTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_DASH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_DOGE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_EOS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_ETC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_ETH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_GRIN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_LTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_STR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_TRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_TUSD",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_USDT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_XMR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_XRP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDC_ZEC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDJ_BTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDJ_BTT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDJ_TRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_AAVE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ADABEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ADABULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ADD",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ADEL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_AKRO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ALPHA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_AMP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ANK",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_API3",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ATOM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_AVA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_AKITA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BAC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BADGER",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BAL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BAND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BAT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BCH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BCHA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BCHBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BCHBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BCHC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BCHSV",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BCN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BDP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BID",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BLY",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BNB",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BOND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BREE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BRG",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BSVBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BSVBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BTT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BUSD",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BVOL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BZRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_BTCST",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_B20",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_CHR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_COMBO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_COMP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_CORN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_CREAM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_CRT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_CRV",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_CUDOS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_CUSDT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_CVP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DAI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DASH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DEC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DEXT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DGB",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DHT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DIA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DOGE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DOS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DOT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_DEGO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_EOS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_EOSBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_EOSBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ESD",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ETC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ETH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ETHBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ETHBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_EXE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ELON",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FARM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FCT2",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FRONT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FSW",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FTT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FUND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FXC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FIL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_FORTH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_GEEQ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_GHST",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_GLM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_GRIN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_GRT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_HEGIC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_HGET",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_IBVOL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_INJ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_JFI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_JST",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_KP3R",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_KTON",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_KCS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_KLV",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LEND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LINK",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LINKBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LINKBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LPT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LON",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LRC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LSK",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LTCBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LTCBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LIVE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LQTY",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_LUSD",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MANA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MATIC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MCB",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MDT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MEME",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MEXP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MKR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MPH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MTA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MIR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_MIST",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_NEO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_NU",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_NFTX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_OCEAN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_OM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ONEINCH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_OPT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_PAX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_PBTC35A",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_PEARL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_PERX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_POLS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_PRQ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_QTUM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_QUICK",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_RARI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_REEF",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_REN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_REPV2",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_RFUEL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_RING",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_RSR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SAL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SAND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SENSO",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SNX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SRM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_STAKE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_STEEM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_STPT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_STR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SUN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SUSHI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SWAP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SWFTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SWINGBY",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SWRV",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SXP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SFI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_SHIB",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TAI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TEND",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TRADE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TRB",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TRU",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TRXBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TRXBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_TUSD",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_UMA",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_UNI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_USDJ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_UST",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_VALUE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_VSP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_WBTC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_WETH",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_WIN",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_WNXM",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_WRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_WHALE",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XFLR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XLMBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XLMBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XMR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XRP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XRPBEAR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XRPBULL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XTZ",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_XOR",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_YFI",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_YFII",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_YFL",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ZAP",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ZEC",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ZKS",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ZLOT",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: uuid(),
          currency_pair: "USDT_ZRX",
          created_at: new Date(),
          updated_at: new Date(),
        },
      ])
      .execute();
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    queryRunner.dropTable("currency");
  }
}
