FROM node:14.15.4

ARG APP_PORT=3333
ARG BASE_URL_API_POLONIEX='https://poloniex.com'
ARG TYPEORM_HOST=server-mysql
ARG TYPEORM_USERNAME=bitbot
ARG TYPEORM_PASSWORD=bitbot
ARG TYPEORM_DATABASE=bitbot
ARG TYPEORM_PORT=3306
ARG TYPEORM_LOGGING=false
ARG TYPEORM_ENTITIES='./src/database/entities/*.ts'
ARG TYPEORM_MIGRATIONS='./src/database/migrations/*.ts'
ARG TYPEORM_MIGRATIONS_DIR='./src/database/migrations'

WORKDIR /project

ADD . .
RUN yarn add typescript
RUN yarn install

RUN echo APP_PORT=${APP_PORT} >> .env
RUN echo BASE_URL_API_POLONIEX=${BASE_URL_API_POLONIEX} >> .env
RUN echo TYPEORM_HOST=${TYPEORM_HOST} >> .env
RUN echo TYPEORM_USERNAME=${TYPEORM_USERNAME} >> .env
RUN echo TYPEORM_PASSWORD=${TYPEORM_PASSWORD} >> .env
RUN echo TYPEORM_DATABASE=${TYPEORM_DATABASE} >> .env
RUN echo TYPEORM_PORT=${TYPEORM_PORT} >> .env
RUN echo TYPEORM_LOGGING=${TYPEORM_LOGGING} >> .env
RUN echo TYPEORM_ENTITIES=${TYPEORM_ENTITIES} >> .env
RUN echo TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS} >> .env
RUN echo TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR} >> .env

EXPOSE $APP_PORT

CMD yarn typeorm migration:run && yarn start