version: "3.1"

services:

  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitbot
      MYSQL_USER: bitbot
      MYSQL_PASSWORD: bitbot
    volumes:
      - ./.docker/db/bddata:/var/lib/mysql
      - ./.docker/db/bdimport:/docker-entrypoint-initdb.d
    ports:
      - 3309:3306
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
